# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".venv",
    ".vscode",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
# enable `E`, `F`, `W`, `Q`, flake8-bugbear (`B`) and flake8-quotes (`Q`).
select = ["E", "F", "W", "Q", "B", "Q"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "lf"
docstring-code-format = false
docstring-code-line-length = "dynamic"
